/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DemoAccountsRouteImport } from './routes/demo-accounts'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAccountsRoute = DemoAccountsRouteImport.update({
  id: '/demo-accounts',
  path: '/demo-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/calculator': typeof CalculatorRoute
  '/charts': typeof ChartsRoute
  '/demo-accounts': typeof DemoAccountsRoute
  '/flashcards': typeof FlashcardsRoute
  '/journal': typeof JournalRoute
  '/levels': typeof LevelsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/calculator': typeof CalculatorRoute
  '/charts': typeof ChartsRoute
  '/demo-accounts': typeof DemoAccountsRoute
  '/flashcards': typeof FlashcardsRoute
  '/journal': typeof JournalRoute
  '/levels': typeof LevelsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/calculator': typeof CalculatorRoute
  '/charts': typeof ChartsRoute
  '/demo-accounts': typeof DemoAccountsRoute
  '/flashcards': typeof FlashcardsRoute
  '/journal': typeof JournalRoute
  '/levels': typeof LevelsRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/calculator'
    | '/charts'
    | '/demo-accounts'
    | '/flashcards'
    | '/journal'
    | '/levels'
    | '/roadmap'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/calculator'
    | '/charts'
    | '/demo-accounts'
    | '/flashcards'
    | '/journal'
    | '/levels'
    | '/roadmap'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/calculator'
    | '/charts'
    | '/demo-accounts'
    | '/flashcards'
    | '/journal'
    | '/levels'
    | '/roadmap'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  CalculatorRoute: typeof CalculatorRoute
  ChartsRoute: typeof ChartsRoute
  DemoAccountsRoute: typeof DemoAccountsRoute
  FlashcardsRoute: typeof FlashcardsRoute
  JournalRoute: typeof JournalRoute
  LevelsRoute: typeof LevelsRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-accounts': {
      id: '/demo-accounts'
      path: '/demo-accounts'
      fullPath: '/demo-accounts'
      preLoaderRoute: typeof DemoAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  CalculatorRoute: CalculatorRoute,
  ChartsRoute: ChartsRoute,
  DemoAccountsRoute: DemoAccountsRoute,
  FlashcardsRoute: FlashcardsRoute,
  JournalRoute: JournalRoute,
  LevelsRoute: LevelsRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
